#!/bin/sh
set -e

case "$1" in
  configure|abort-upgrade|abort-remove|abort-deconfigure)
    if command -v udevadm >/dev/null 2>&1; then
      udevadm control --reload-rules || true
      udevadm trigger --subsystem-match=hidraw || true
      udevadm trigger --name-match=uinput || true
    fi
    ;;
esac

#DEBHELPER#

exit 0
