#!/bin/sh
set -e

case "$1" in
  remove|purge)
    if command -v udevadm >/dev/null 2>&1; then
      udevadm control --reload-rules || true
      udevadm trigger --subsystem-match=hidraw || true
      udevadm trigger --name-match=uinput || true
    fi
    ;;
esac

# Automatically added by dh_installsystemduser/13.24.2ubuntu1
if [ "$1" = "purge" ]; then
	if [ -z "$DPKG_ROOT" ] && [ -x "/usr/bin/deb-systemd-helper" ] ; then
		deb-systemd-helper --user purge 'swift-touch-media.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
